theme: jekyll-theme-minimal
title: Henry J. Nelson
description: I'm currently a PhD student at the University of Minnesota working on 3D computer vison with applications in medicine and precision agriculture. See my résumé for contact information.
logo: images/logo.jpg
