theme: jekyll-theme-minimal
title: Henry J. Nelson
description: I have recently finished my PhD at the University of Minnesota working on 3D computer vision with applications in precision agriculture. See my résumé for contact information.
logo: images/logo.jpg
